KERNEL_DEVICETREE = "aspeed/aspeed-ast2500-custom-board.dtb"

UBOOT_MACHINE = "evb-ast2500_defconfig"
UBOOT_DEVICETREE = "ast2500-evb"

# require conf/machine/evb-ast2500.conf
require conf/machine/include/ast2500.inc
require conf/machine/include/obmc-evb-common.inc

MACHINEOVERRIDES =. "custom-board:"

SERIAL_CONSOLES = "115200;ttyS4"

FLASH_SIZE = "65536"
